### ISSUE TITLE
[HEADER] Arrow down-button

### ISSUE THREAD

**Issue by Oekidoebi** [Oekidoebi/GiroDiMolveno#10]
Op de homepage (header-sectie) moet onder aan in het midden een ronde button met arrow komen zodat, als je daar op drukt, je naar de volgende sectie scrolt
Eigenlijk zoals bij spirit8 (site2): 
http://themeforces.com/demo/freebies/tf-free-no.3/
Ander voorbeeld (maar gewoon rond knopje met arrow down zoals bij spirit8 vind ik mooier):
http://www.jdcdesignstudio.com/

Deze button hoeft wat mij betreft alleen in deze sectie. 
Voor het scrollen naar volgende sectie moet je knopje geloof ik in een div zetten met class page-scroll

**Comment by rwaaijman** [comment]
done

**Comment by Oekidoebi** [comment]
Het kan nog zijn dat dit knopje altijd onderaan de header-sectie moet komen maar dan zo dat ie altijd zichtbaar is in het scherm zonder te hoeven scrollen. Dat is dus afhankelijk van schermgrootte en rotatie en vereist waarschijnlijk javascript (misschien alleen css). Maar dat zien we vrijdag wel....
