### ISSUE TITLE
Offerte formulier

### ISSUE THREAD

**Issue by Oekidoebi** [Oekidoebi/GiroDiMolveno#14]
Onder 'Contact' staat een button 'Offerte'. Als daarop geklikt wordt moet er zo'n popup (modal) geopend worden met een formuliertje dat mensen kunnen invullen en kunnen verzenden.
Dingen die erop moeten:
- Of de offerte voor Giro di Molveno is of Pas op voor Pasta (of beide?) (verplicht veld)
- Groepsgrootte (verplicht veld, zou ook kunnen als keuzemogelijkheid 5-10, 10-15, 15-20, 20-25....)
- Periode (verplicht veld)
- Aantal dagen (verplicht veld, dropdown?)
- Met/zonder volgauto/picnic/pasta/...?
- Naam
- Emailadres (verplicht veld)
- Textarea, ruimte voor berichtje

Daaronder een 'Verzenden' knop waarmee form wordt verstuurd en de popup (modal) wordt afgesloten.

**Comment by rwaaijman** [comment]
Afgerond, eventueel later nog aanvullen
