### ISSUE TITLE
Google map in locatie div

### ISSUE THREAD

**Issue by Oekidoebi** [Oekidoebi/GiroDiMolveno#17]
Ff snel gegoogled, weet niet of hier wat tussen zit:
http://www.bootply.com/77513
http://www.bootstrapzero.com/bootstrap-template/google-maps
https://github.com/Esri/bootstrap-map-js
http://stackoverflow.com/questions/26841084/how-to-embed-google-map-using-bootstrap

**Comment by rwaaijman** [comment]
Gekozen voor een plaatje met link naar google maps
