### ISSUE TITLE
Locatie

### ISSUE THREAD

**Issue by Oekidoebi** [Oekidoebi/GiroDiMolveno#4]
Sectie is/wordt een combi van tekst (tekst staat er deels al), foto's en een schematisch plattegrondje.
Over nadenken hoe dat op een leuke/goede manier te doen. Schetsje maken, voorbeeldjes zoeken.
Hoe/Waarmee maken we schematische plattegrondje?

-- Nog niet maken, maar ff uitzoeken

**Comment by Oekidoebi** [comment]
https://www.google.nl/search?q=come+arrivare+stelvio&rlz=1C9BKJA_enNL597NL597&hl=nl&source=lnms&tbm=isch&sa=X&ved=0CAkQ_AUoAmoVChMI66K2t9j0xwIV4XxyCh1J5gcQ&biw=1024&bih=653#hl=nl&tbm=isch&q=come+arrivare+molveno&imgrc=H44Zrm8Uah8CKM%3A

**Comment by rwaaijman** [comment]
Heb tabs iets aangepast. Nog niet helemaal tevreden. Als je erop staat zou het semi-transparant moeten zijn (zoals na het verversen van website..). Wanneer je het activeert wordt het rood (werkt).

**Comment by Oekidoebi** [comment]
Zie ook issue 17 mbt google mapje
