### ISSUE TITLE
Menu-bar

### ISSUE THREAD

**Issue by Oekidoebi** [Oekidoebi/GiroDiMolveno#8]

**Comment by rwaaijman** [comment]
wat moet hiermee gebeuren?

**Comment by Oekidoebi** [comment]
Werkt niet helemaal mooi meer. Met klikken en scrollen, active item blijft soms op rood staan. Was denk ik wat te enthousiast met css... is ook niet zo belangrijk, dus laat maar even...

**Comment by Oekidoebi** [comment]
Er moet een dropdown onder 'Aanbod' komen met twee opties: 1) Giro di Molveno; 2) Pas op voor Pasta. Dit moet tevens goed werken in het opgevouwde (responsive) menu.

**Comment by rwaaijman** [comment]
Zit dropdown menu bij. Lukt echter nog niet om aanbod zelf ook aanklikbaar te maken (href naar #vvf-program). Of menu klapt niet open, of aanbod-link werkt niet...

**Comment by Oekidoebi** [comment]
Trekmenu aanbod in mobiele variant werkt niet

**Comment by rwaaijman** [comment]
in freelancer.js script uitgezet die ervoor zorgt dat je menu steeds dicht klapt. Nu blijft menu open staan tot je wederom op menu klikt
