### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Oekidoebi** [Oekidoebi/GiroDiMolveno#9]
Welke informatie moet er in de footer?

**Comment by rwaaijman** [comment]
Disclaimer.
We kunnen ook geen footer doen

-------- Oorspronkelijk bericht --------
Van: Oekidoebi notifications@github.com 
Datum: 11-09-2015  17:13  (GMT+01:00) 
Aan: Oekidoebi/GiroDiMolveno GiroDiMolveno@noreply.github.com 
Onderwerp: [GiroDiMolveno] Footer (#9) 

Welke informatie moet er in de footer?
